### ISSUE TITLE
Using in multiple partial view

### ISSUE THREAD

**Issue by timmyshih** [alexanderar/Mvc.CascadeDropDown#6]
Hi Alexanderar/Author, 

Thanks for provide such helper that can easily build a cascading dropdownlist, while in my case I'm having multiple partial views (can be add/remove by user) and there is a pair of cascade ddl in each one of them, structured like 

-Main View 
- PV1 - 2 DDL
- PV2 - 2 DDL
  ......

Only the DDLs in PV1 (Partial View 1) is cascading, yet others not functioning, after selecting first ddl the second ddl is not retrieving the related data. The code of ddls in PV are below,

`
        @Html.DropDownListFor(m => m.Type, Model.ConditionTypes, "Please select a Country", new { @class = "form-control", id = "Type", name = "Type" })`

```
    @Html.CascadingDropDownListFor(expression: m => m.Operator,
                            triggeredByProperty: m => m.Type,
                            url: Url.Action("GetOperator", "Job"),
                            ajaxActionParamName: "type",
                            optionLabel: "Please select a City",
                            disabledWhenParrentNotSelected: false,
                            htmlAttributes: new { @class = "form-control", id= "Operator", name = "Operator" })
```

I was wondering the cause might be these ddls having same id/name across partial views? Is it possible using Mvc.CascadeDropDown across multiple partial views? 

Thanks in advance.

Tim.

**Comment by alexanderar** [comment]
Hey Tim

I am glad that you found CascadeDropDown extension helpful.

Regarding your issue:

You are correct with your assumption that the issue is caused by duplicate ids. Actually according to [W3C specification, id has to be unique per document](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute). So using the same partial view multiple times the way that you describe is very problematic (_not only for CascadeDropDown_). You have multiple options to solve this issue:
1. Use [EditorTemplates ](https://msdn.microsoft.com/en-us/library/system.web.mvc.html.editorextensions.editorfor%28v=vs.118%29.aspx) instead of partial views wherever it is appropriate.
2.  Specify unique id (using the same name is OK) through `htmlAttributes`:

PV1:

```
 @Html.DropDownListFor(m => m.Type, Model.ConditionTypes, "Please select a Country", new { @class = "form-control", id = "Type1"})
 @Html.CascadingDropDownListFor(expression: m => m.Operator,
                            triggeredByProperty: m => m.Type,
                            url: Url.Action("GetOperator", "Job"),
                            ajaxActionParamName: "type",
                            optionLabel: "Please select a City",
                            disabledWhenParrentNotSelected: false,
                            htmlAttributes: new { @class = "form-control", id= "Operator1" })
```

PV2:

```
@Html.DropDownListFor(m => m.Type, Model.ConditionTypes, "Please select a Country", new { @class = "form-control", id = "Type2"})
@Html.CascadingDropDownListFor(expression: m => m.Operator,
                            triggeredByProperty: m => m.Type,
                            url: Url.Action("GetOperator", "Job"),
                            ajaxActionParamName: "type",
                            optionLabel: "Please select a City",
                            disabledWhenParrentNotSelected: false,
                            htmlAttributes: new { @class = "form-control", id= "Operator2" })
```

Please let me know if it helped to resolve the issue

**Comment by timmyshih** [comment]
Hi Alexanderar, 

Thanks for your kind reply. I've gone through method 2 (specifying unique id for DDLs in each PVs) and even worse, the DDLs in PV1 stop cascading (no matter how many PVs) , after a few try seems the id of ddl1 needs to be exactly the same to property's name (in my case it has to be set to "Type"). 
This is so far as I know, while method 1 takes more time to re-structure my code, I'll let you know if I got it work or not.

 And thanks again!

Tim.

**Comment by alexanderar** [comment]
Tim,

I partially mislead you in my previous answer. Since you are specifying custom id for trigger dropdown, you need to use other Helper method in which you can specify the id of a trigger dropdown through string and not through expression 

```
@Html.DropDownListFor(m => m.Type, Model.ConditionTypes, "Please select a Country", new { @class = "form-control", id = "Type1"})

@Html.CascadingDropDownListFor(
   expression: m => m.Operator,
   triggeredByPropertyWithId: "Type1",
   url: Url.Action("GetOperator", "Job"),
   ajaxActionParamName: "type",
   optionLabel: "Please select a City",
   disabledWhenParentNotSelected: false,
   htmlAttributes: new { @class = "form-control", id= "Operator1" })
```

Notice that instead of passing  `triggeredByProperty: m => m.Type` expression  you need to pass the string representation of an id of the first dropdown which is "Type1" in this example.

It should solve your issue

**Comment by timmyshih** [comment]
Alexanderar,

Assigning id to triggeredByPropertyWithId: method actually works, and according to your suggestion I'm now putting these DDLs inside a custom EditorTemplates, which looks really great and more reasonable for what I'm trying to achieve.

note: while changing the line triggeredByProperty: to triggeredByPropertyWithId: I found that there is a typo in triggeredByProperty: method

```
@Html.CascadingDropDownListFor(expression: m => m.Operator,
                            triggeredByProperty: m => m.Type,
                            url: Url.Action("GetOperator", "Job"),
                            ajaxActionParamName: "type",
                            optionLabel: "Please select a City",
                            disabledWhenParrentNotSelected: false,   //double r for parent
                            htmlAttributes: new { @class = "form-control", id= "Operator2" })
```

Many thanks for solving my issue.

Tim.
